### ISSUE TITLE
Proposal for downloading from SpinShare feature

### ISSUE THREAD

**Issue by LauraWebdev** [kylefmohr/Play_Random_SRXD_Custom#1]
I've just seen the code to randomly select a chart and download it from SpinShare.

You can use the SearchCharts API call and provide an empty query, you receive an array of all charts on SpinShare. You can then use the other parameters to filter out specific difficulties or specify a difficulty range.

The API call takes a few seconds and responds back quite some data, but you could theoretically just call this once and cache the data received.

https://spinsha.re/api/docs/open/discovery#searchCharts

**Comment by kylefmohr** [comment]
Thanks! I'm on it.

**Comment by kylefmohr** [comment]
Do you think it's reasonable to make that API call every time a user first launches the script? The amount of time it takes is very reasonable, especially since it would only happen once per script launch. But I don't want to unnecessarily hammer the spinsha.re server. 

Otherwise I can check if the cache exists on the filesystem, and maybe check the modified date on the cache file to see if it needs to be updated online. 

Also I just noticed the /songs/new/ API, sweet! I can remove a rather large dependency.

**Comment by LauraWebdev** [comment]
It does feel like a "startup" thing to do. It wouldn't flush the SpinShare servers too much I think.

**Comment by kylefmohr** [comment]
Implemented in 1b4e12f9b80986d16fdb78b5f47eb1688cfa16a8, thanks again!

**Comment by LauraWebdev** [comment]
Just as a little tip: Since users define their wanted difficulties and difficulty range, you could add them to the payload as filters and get a significantly smaller cache/faster cache creation.
